import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { OttGeneratedModule, OttGeneratedSharedModule } from './generated/module.js';
import { OttValidator, registerValidationChecks } from './ott-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type OttAddedServices = {
    validation: {
        OttValidator: OttValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type OttServices = LangiumServices & OttAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const OttModule: Module<OttServices, PartialLangiumServices & OttAddedServices> = {
    validation: {
        OttValidator: () => new OttValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createOttServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Ott: OttServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        OttGeneratedSharedModule
    );
    const Ott = inject(
        createDefaultModule({ shared }),
        OttGeneratedModule,
        OttModule
    );
    shared.ServiceRegistry.register(Ott);
    registerValidationChecks(Ott);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Ott };
}
